### PR TITLE
the newer RVL-CNT-01-TR (MotionPlus Inside)

### PR DESCRIPTION
**Pull request by xoyojank**
* merge from https://github.com/Kalabasa/supertuxkart-remote-controller/blob/master/SuperTuxKart-0.8.1/lib/wiiuse/
to support the newer RVL-CNT-01-TR (MotionPlus Inside)

### CODE REVIEW

**Comment by janoc** [comment]
@rpavlik do you think we can merge this? I would perhaps rename the constant WIIUSE_WIIMOTE_MOTION_PLUS_INSIDE because there is an older (non -TR) Wiimote+ that had Motion+. That one uses the same IDs as a regular old Wiimote with the external Motion+ dongle (I have one of them). It should be made explicit to which Wiimote version this refers to, IMO.

**Comment by xoyojank** [comment]
I found a problem: the pitch,yaw, roll are always zero, because the cal_g is always zero. 
Is there any idea to fix that?


	/* if the accelerometer is turned on then print angles */
	if (WIIUSE_USING_ACC(wm)) {
		printf("wiimote roll  = %f [%f]\n", wm->orient.roll, wm->orient.a_roll);
		printf("wiimote pitch = %f [%f]\n", wm->orient.pitch, wm->orient.a_pitch);
		printf("wiimote yaw   = %f\n", wm->orient.yaw);
	}

**Comment by janoc** [comment]
That looks like the accelerometer calibration has failed for whatever reason. It would help to compile Wiiuse in debug mode and post the debug output from one of the examples. It is possible that your new Wiimote has the calibration data in either a different format or stored in a different place in memory compared to the classic one. 

However, could you open a separate issue for this problem unless it got broken by the above pull request, please? It is best to not mix issues.

**Comment by xoyojank** [comment]
I revert some changes, and it works now. the yaw is always 0, but the rotation data of Motion Plus is right now.

**Comment by janoc** [comment]
Ah yes, I see. Makes sense. 

Yaw being 0 when you don't have Motion+ enabled is completely normal and intended - accelerometer cannot give you yaw (rotation in the horizontal around the gravity vector). Once you enable Motion+ you should get yaw from the gyro and the value will be valid.

**Comment by rpavlik** [comment]
If you're fine with the merge so am I

**Comment by janoc** [comment]
Well, lets merge it then. I think that will allow to close the issue #21 as well.

**Comment by rpavlik** [comment]
OK, merging.  Note that I think you have "collaborator" status which should allow you to merge stuff unilaterally.

**Pull request merged**
