### PR TITLE
Nintendo RVL-CNT-01-TR support on Windows

### PR DESCRIPTION
**Pull request by mathsomal**
Added Nintendo RVL-CNT-01-TR support for Windows. Only little changes to recognize the new WiiMotes with their product id. Modifications are tested on Windows, everything seems to work well.

### CODE REVIEW

**Comment by janoc** [comment]
Hi, 

Thanks for the patch, but could you, please, add that line to the Linux & Mac code too? 

Even if untested - someone will test it, but it is, IMO, better to have something obviously broken than to have a feature difference like this between platforms without explanation.

**Comment by rpavlik** [comment]
Oh I am excited about this! Yes, please give it a try on Linux and Mac.

**Comment by janoc** [comment]
On Fri, Feb 6, 2015 at 4:43 PM, Ryan Pavlik <notifications@github.com>
wrote:

> Oh I am excited about this! Yes, please give it a try on Linux and Mac.
>

I can try to compile it, but I don't have the new Wiimote, so that isn't
going to help much.

**Comment by mathsomal** [comment]
I thought Mac support has already been implemented last year: 
https://github.com/rpavlik/wiiuse/commit/fdc30d34147be64d2b334e42fc7648a5ef09464b

Not sure about linux, though.

For those using Windows, also be aware to connect the devices the right way, otherwise it won't work:
https://wiki.dolphin-emu.org/index.php?title=Wii_Remote_Plus_%28RVL-CNT-01-TR%29_Connection_Guide

**Comment by qwertychouskie** [comment]
Any chance of getting this merged?

**Comment by janoc** [comment]
That code needs update and needs testing. Unless you are willing to step up and test it, then it is not likely to get merged. Neither me nor Ryan have the affected hardware and there is Mac support to test that neither of us has.

**Comment by qwertychouskie** [comment]
I just checked and this code is already in master, so this should be closed.

**Comment by janoc** [comment]
@qwertychouskie

Are you sure? I have checked and I don't see this in the master. It also needs to be tested for Mac & Linux by someone who actually has the -TR type of wiimote.

**Comment by qwertychouskie** [comment]
https://github.com/rpavlik/wiiuse/blob/master/src/os_win.c#L118 and https://github.com/rpavlik/wiiuse/blob/master/src/wiiuse_internal.h#L172.  Note that it is called `WM_PLUS_PRODUCT_ID` instead of `WM_PRODUCT_ID_TR`, is in this PR.

**Comment by janoc** [comment]
Hmm, I see. That's rather unfortunate naming, because there there are 3 versions of the Wiimote: 

* original
* original + Motion Plus
* new -TR + Motion Plus

**Comment by qwertychouskie** [comment]
Best I know, the original + Motion Plus is read the same as the original.

**Comment by janoc** [comment]
Yes, it is. Just the name of that constant is misleading and could be confused. 
I have checked the Linux code, that one works the same as the Mac one, only Windows actually uses these constants. So I guess I will merge it and pray.

**Pull request merged**
